Initial release.
devgeniem/wp-cron-runner pull request #1
Opened 2017-11-15 12:55 UTC by villesiltala

This mu-plugin is created for our pipeline to enable running WP cron jobs easily via a single endpoint for a WordPress site whether it is a network installation or not.

2017-11-15 14:12 UTC, You-Honey requested changes

2017-11-15 14:12 UTC, JuhaniGeniem commented on plugin.php
> +    );
```
Toi negaatiokikkailu on tosi vaikeasti luettavaa.

Tekistkö tää saman asian?

$is_not_authenticated = (
  empty( $_SERVER['PHP_AUTH_USER'] ) ||
  empty( $_SERVER['PHP_AUTH_PW'] ) ||
  $_SERVER['PHP_AUTH_USER'] !== $user ||
  $_SERVER['PHP_AUTH_PW'] !== $pw
);
```

2017-11-15 14:20 UTC, villesiltala commented on plugin.php
> +        if ( is_array( $blogs ) ) {
Katso coren [kommentti](https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L2495) palautusarvosta. `is_array()` on siitä näpsäkkä, että `foreach` ei ajaudu myöskään silloin, jos taulukko on tyhjä muttei myöskään palauta varoitusta.

2017-11-15 15:08 UTC, JuhaniGeniem commented on plugin.php
> +        if ( is_array( $blogs ) ) {
Joo niin se toimia mutta miks haluat mennä iffin sisään ja ajaa tyhjän foreachin turhaan kun vois vaan olla menemättä koko iffiin jos se array on tyhjä? :o 

Ja myös jos joku myöhemmin lisää sinne foreachin perään jotain koodia kun ajattelee, että se ajautuu vaan jos siellä oli jotain mitä ajaa niin voi tulla ongelmia.

2017-11-16 06:00 UTC, villesiltala commented on plugin.php
> +        if ( is_array( $blogs ) ) {
En suosi emptyn käyttämistä tilanteissa, joissa tyypillä on merkitystä. Empty voi aiheuttaa ongelmia, kun se ei tässä tiedä palautusarvon tyypistä mitään. Silloin tästä voisi päästä läpi stringit, integerit ja oliot. :o Tässä nimenomaisessa tapauksessa `get_results()` voi palauttaa myös `WP_Error`-olion, jota lähdettäisiin luuppaamaan foreachissa. Silloin koodi aiheuttaisi ainakin warningin ja odottamatonta toimintaa, kun `$blog->domain` ei olisikaan olemassa. Se onkin sitten toinen kysymys, pitäisikö tässä parantaa kokonaisuudessaan virheenkäsittelyä ja lopettaa suoritus `WP_Error`-olion palautuessa.

2017-11-16 09:45 UTC, JuhaniGeniem commented on plugin.php
> +        if ( is_array( $blogs ) ) {
Hyviä pointteja. Ehkä kaikista fiksuin ratkaisu olisi sitten tehdä is_array ja !empty :D

2017-11-16 11:31 UTC, You-Honey approved these changes

2017-11-16 12:29 UTC, merged